receivers:
  otlp:
    protocols:
      grpc:

exporters:

  otlp:
    endpoint: http://tempo:4317
    tls:
      insecure: true

  logging:
    verbosity: detailed
    sampling_initial: 5
    sampling_thereafter: 200

service:
  pipelines:
    traces:
      receivers:
        - otlp
      exporters:
        - otlp
        - logging
