server:
  port: 8080
  servlet:
    context-path: /api
spring:
  application:
    name: microservices-meetup.com

management:
  endpoints:
    web:
      exposure:
        include: '*'
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true
    tags:
      application: ${spring.application.name}
  tracing:
    sampling:
      probability: 1.0

logging:
#  level:
#    org.springframework.web: DEBUG
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"